# --------------------------------- PowerCamera ---------------------------------
# Create cinematic views on your server
# -------------------------------------------------------------------------------
#                                point-preview-time
# Set the preview duration of a point in seconds
# -------------------------------------------------------------------------------
#                                     on-join
# random-player-camera-path: Choose a random camera path to show when a new player joins
# show-once: <true/false>
#   true, show the camera path once for new players
#   false, show the camera path always when a players joins
# -------------------------------------------------------------------------------
#                                 camera-effects
# invisible: Set the player as invisible while the camera is active
# spectator-mode: Set the player as spectator while the camera is active
# -------------------------------------------------------------------------------

point-preview-time: 5
on-join:
  random-player-camera-path: []
  show-once: true
camera-effects:
  invisible: false
  spectator-mode: true